### ISSUE TITLE
Parameter grouping doesn't work with new Jenkins versions

### ISSUE THREAD

**Issue by nosmoke** [Eccenux/jenkins-scripts#2]
I'm running on Jenkins version 2.235.5, and it appears that the parameter grouping script doesn't work.
After checking the reason, I noticed that the problem is that checkboxes (boolean parameter) don't show their names like other parameters, and the script fails in the following line that initialize the Parameter name:
`this.name = "" + parameterBody.querySelector(".setting-name").textContent;`

I have changed it locally to this, and now it works:
`this.name = "" + parameterBody.querySelector(".setting-main > div > input[name=name]").value;`

**Comment by Eccenux** [comment]
Just `parameterBody.querySelector("input[name=name]").value` seems fine too and should be more stable.
